# Generated by Django 4.1.5 on 2023-06-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SL_No", models.IntegerField()),
                ("Item_Name", models.CharField(max_length=250)),
                ("Description", models.CharField(max_length=250)),
            ],
        ),
    ]
